/**
 * Phase 2 — pre-Supabase local gallery optimizer.
 *
 * Picks a curated subset of the 1.8GB asset library, generates two
 * WebP variants (800w / 1600w), encodes a blurhash for blur-up, and
 * writes lib/gallery/manifest.ts.
 *
 * Run once locally:
 *   npx tsx scripts/optimize-local-gallery.ts
 *
 * The optimized files land in /public/gallery/<category>/<slug>-<w>.webp
 * and ship with the Vercel deploy (≈10MB total). When Supabase lands,
 * we point next/image at the CDN and stop shipping these in /public.
 */

import sharp from "sharp";
import { promises as fs } from "node:fs";
import { join, basename, extname } from "node:path";

// ---- Configuration ---------------------------------------------------------

const SOURCE_ROOT = "assets/sorted";
const OUT_ROOT = "public/gallery";
const MANIFEST_PATH = "lib/gallery/manifest.ts";
const VARIANTS = [800, 1600] as const;

// Curated subset — first N files per directory, sorted alphabetically.
// Adjust counts if /public weight needs to shrink.
const SUBSETS: Record<GalleryCategory, { dir: string; take: number }> = {
  listings: { dir: "ecommerce-listing", take: 10 },
  lifestyle: { dir: "ecommerce-lifestyle", take: 14 },
  "white-bg": { dir: "main-listing-white-bg", take: 6 },
};

type GalleryCategory = "listings" | "lifestyle" | "white-bg";

// ---- Types ----------------------------------------------------------------

type ManifestEntry = {
  id: string;
  category: GalleryCategory;
  brand: string;
  slug: string;
  alt: string;
  width: number;
  height: number;
  blurDataURL: string;
  variants: { 800: string; 1600: string };
};

type Manifest = Record<GalleryCategory, ManifestEntry[]>;

// ---- Main -----------------------------------------------------------------

async function main() {
  const manifest: Manifest = {
    listings: [],
    lifestyle: [],
    "white-bg": [],
  };

  for (const [categoryKey, cfg] of Object.entries(SUBSETS) as [
    GalleryCategory,
    { dir: string; take: number },
  ][]) {
    const sourceDir = join(SOURCE_ROOT, cfg.dir);
    const outDir = join(OUT_ROOT, categoryKey);

    let files: string[];
    try {
      files = (await fs.readdir(sourceDir))
        .filter((f) => /\.(jpe?g|png|webp)$/i.test(f))
        .sort()
        .slice(0, cfg.take);
    } catch (err) {
      console.warn(`[opt] skipping ${categoryKey} (${(err as Error).message})`);
      continue;
    }

    await fs.mkdir(outDir, { recursive: true });
    console.log(`[opt] ${categoryKey}: ${files.length} files → ${outDir}`);

    for (const file of files) {
      const src = join(sourceDir, file);
      const slug = sanitizeSlug(basename(file, extname(file)));
      const meta = await sharp(src).metadata();
      const aspect = (meta.height ?? 1) / (meta.width ?? 1);

      // WebP variants
      for (const width of VARIANTS) {
        const out = join(outDir, `${slug}-${width}.webp`);
        await sharp(src)
          .resize({ width, withoutEnlargement: true })
          .webp({ quality: 78, effort: 5 })
          .toFile(out);
      }

      // Tiny 16px webp encoded base64 for next/image's blur placeholder
      // (~300 bytes per image, lazy-decoded by the browser natively)
      const blurBuffer = await sharp(src)
        .resize({ width: 16 })
        .webp({ quality: 30 })
        .toBuffer();
      const blurDataURL = `data:image/webp;base64,${blurBuffer.toString("base64")}`;

      manifest[categoryKey].push({
        id: `${categoryKey}/${slug}`,
        category: categoryKey,
        brand: inferBrand(file),
        slug,
        alt: humanizeSlug(slug),
        width: meta.width ?? 1024,
        height: meta.height ?? 1024,
        blurDataURL,
        variants: {
          800: `/gallery/${categoryKey}/${slug}-800.webp`,
          1600: `/gallery/${categoryKey}/${slug}-1600.webp`,
        },
      });
    }
  }

  // Synthesize a "social" tab from a subset of lifestyle — cropped 9:16
  // at render-time via next/image. Lets us tab without generating new files.
  const socialEntries: ManifestEntry[] = manifest.lifestyle
    .slice(0, 8)
    .map((e) => ({ ...e, id: `social/${e.slug}`, category: "lifestyle" as const }));

  await fs.mkdir("lib/gallery", { recursive: true });
  const out = `// AUTO-GENERATED by scripts/optimize-local-gallery.ts — do not edit by hand.
// Re-run the script to refresh after adding new assets.

export type GalleryCategory = "listings" | "lifestyle" | "white-bg";

export type GalleryEntry = {
  id: string;
  category: GalleryCategory;
  brand: string;
  slug: string;
  alt: string;
  width: number;
  height: number;
  blurDataURL: string;
  variants: { 800: string; 1600: string };
};

export const MANIFEST: Record<GalleryCategory, GalleryEntry[]> = ${JSON.stringify(
    manifest,
    null,
    2,
  )};

export const SOCIAL_PREVIEW: GalleryEntry[] = ${JSON.stringify(socialEntries, null, 2)};

// Tab → entries — "social" is a curated subset of lifestyle for now.
export const TABS = {
  listings: [...MANIFEST.listings, ...MANIFEST["white-bg"]],
  lifestyle: MANIFEST.lifestyle,
  social: SOCIAL_PREVIEW,
};
`;
  await fs.writeFile(MANIFEST_PATH, out, "utf-8");

  const total = Object.values(manifest).reduce((s, a) => s + a.length, 0);
  console.log(`[opt] wrote ${MANIFEST_PATH} — ${total} entries`);
}

// ---- Helpers --------------------------------------------------------------

function sanitizeSlug(name: string) {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9-]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function humanizeSlug(slug: string) {
  return slug
    .replace(/[-_]/g, " ")
    .replace(/\b\w/g, (c) => c.toUpperCase())
    .replace(/\d{4}/g, "");
}

function inferBrand(filename: string): string {
  const lower = filename.toLowerCase();
  if (/terra|balm|soap|oil|sunscreen|deod/.test(lower)) return "terra-lotus";
  return "terra-lotus"; // single-brand showcase for now
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
