// AUTO-GENERATED by scripts/optimize-local-gallery.ts — do not edit by hand.
// Re-run the script to refresh after adding new assets.

export type GalleryCategory = "listings" | "lifestyle" | "white-bg";

export type GalleryEntry = {
  id: string;
  category: GalleryCategory;
  brand: string;
  slug: string;
  alt: string;
  width: number;
  height: number;
  blurDataURL: string;
  variants: { 800: string; 1600: string };
};

export const MANIFEST: Record<GalleryCategory, GalleryEntry[]> = {
  "listings": [
    {
      "id": "listings/listing-0001",
      "category": "listings",
      "brand": "terra-lotus",
      "slug": "listing-0001",
      "alt": "Amazon listing hero with product shot and infographic tiles",
      "width": 2048,
      "height": 2048,
      "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADwAQCdASoQABAABABoJZQAAtz9ioxuDgAA/u3g6zIa1cnVGbfPPv8JAfBE11OhNmdt+6HaNUT3nDad+6hMTeMw+k7qMcGM+fapIInKmRvG3rBUAAA=",
      "variants": {
        "800": "/gallery/listings/listing-0001-800.webp",
        "1600": "/gallery/listings/listing-0001-1600.webp"
      }
    },
    {
      "id": "listings/listing-0002",
      "category": "listings",
      "brand": "terra-lotus",
      "slug": "listing-0002",
      "alt": "Amazon listing hero with product shot and infographic tiles",
      "width": 2048,
      "height": 2048,
      "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAAAwAgCdASoQABAABABoJYwCdAERH6w1sLnSAAD+9NvOqJF+Hf3Dn20twO/OoWHIE3sue8RS5HvH3JISFT9hQkss0TDzrFbRC1PmAAAA",
      "variants": {
        "800": "/gallery/listings/listing-0002-800.webp",
        "1600": "/gallery/listings/listing-0002-1600.webp"
      }
    },
    {
      "id": "listings/listing-0003",
      "category": "listings",
      "brand": "terra-lotus",
      "slug": "listing-0003",
      "alt": "Amazon listing hero with product shot and infographic tiles",
      "width": 2048,
      "height": 2048,
      "blurDataURL": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAQAgCdASoQABAABABoJYwC7AELZQE459NAAP7t4OsyGtXJ1RvjGGw7dnxH9W3IUOHuzZfmH4l1vwYvLrurYAOyXNGjidEXd2XPciiDpy7B17OS08AAAA==",
      "variants": {
        "800": "/gallery/listings/listing-0003-800.webp",
        "1600": "/gallery/listings/listing-0003-1600.webp"
      }
    },
    {
      "id": "listings/listing-0004",
      "category": "listings",
      "brand": "terra-lotus",
      "slug": "listing-0004",
      "alt": "Amazon listing hero with product shot and infographic tiles",
      "width": 2048,
      "height": 2048,
      "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADQAQCdASoQABAABABoJZQAAueL3Iy1YAD+9M9RnTqqqE5VbWxa+clo0KcxDJ3LsfLqb/bw7lwd7iSMpgu+0bpGNKlvcssNdpZgAA==",
      "variants": {
        "800": "/gallery/listings/listing-0004-800.webp",
        "1600": "/gallery/listings/listing-0004-1600.webp"
      }
    },
    {
      "id": "listings/listing-0005",
      "category": "listings",
      "brand": "terra-lotus",
      "slug": "listing-0005",
      "alt": "Amazon listing hero with product shot and infographic tiles",
      "width": 1024,
      "height": 1024,
      "blurDataURL": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAACwAQCdASoQABAABABoJaQAAua8P58AAP72Bghs3xTfqa74PnU1fMeXEsskPp6lD+mU1S4eqfTymAAA",
      "variants": {
        "800": "/gallery/listings/listing-0005-800.webp",
        "1600": "/gallery/listings/listing-0005-1600.webp"
      }
    },
    {
      "id": "listings/listing-0006",
      "category": "listings",
      "brand": "terra-lotus",
      "slug": "listing-0006",
      "alt": "Amazon listing hero with product shot and infographic tiles",
      "width": 1536,
      "height": 1024,
      "blurDataURL": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADwAQCdASoQAAsABABoJZQCdAEN3TkjNgAA/vOT22r4eSb2mfEPjZTDr1VcHFi6BXFhmET9mjZfesBA9ayH0R1eyGD3RVQA",
      "variants": {
        "800": "/gallery/listings/listing-0006-800.webp",
        "1600": "/gallery/listings/listing-0006-1600.webp"
      }
    },
    {
      "id": "listings/listing-0007",
      "category": "listings",
      "brand": "terra-lotus",
      "slug": "listing-0007",
      "alt": "Amazon listing hero with product shot and infographic tiles",
      "width": 2048,
      "height": 2048,
      "blurDataURL": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAABQAgCdASoQABAABABoJaACdADp+eMBfXUqI2AA+LMz6sfu+tFfiRtMIACmXYlrZ/va363OXD1EmCA1FEJN7x8WgMHBWnfPiQxN+ppFdd561rur1PpgswnlJo4YF4kzFWWkd4AA",
      "variants": {
        "800": "/gallery/listings/listing-0007-800.webp",
        "1600": "/gallery/listings/listing-0007-1600.webp"
      }
    },
    {
      "id": "listings/listing-0008",
      "category": "listings",
      "brand": "terra-lotus",
      "slug": "listing-0008",
      "alt": "Amazon listing hero with product shot and infographic tiles",
      "width": 2048,
      "height": 2048,
      "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAQAgCdASoQABAABABoJQBOgCHwytQiOlYQAP7XgcSq08A22KtlTVF7C8eO6pOVPrDECSdZrPCWCVFFv+j00GmGsLaPQ/bouFKniQTwK022gBoeurUh0AAA",
      "variants": {
        "800": "/gallery/listings/listing-0008-800.webp",
        "1600": "/gallery/listings/listing-0008-1600.webp"
      }
    },
    {
      "id": "listings/listing-0009",
      "category": "listings",
      "brand": "terra-lotus",
      "slug": "listing-0009",
      "alt": "Amazon listing hero with product shot and infographic tiles",
      "width": 2048,
      "height": 2048,
      "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADwAQCdASoQABAABABoJYwC7AEO/73dzFAA/vJyLlBIywn7jLXbH4nEop52qt+dtTZf8aZ8dE1hA4fceaMqNglvY7sNUFG4gAA=",
      "variants": {
        "800": "/gallery/listings/listing-0009-800.webp",
        "1600": "/gallery/listings/listing-0009-1600.webp"
      }
    },
    {
      "id": "listings/listing-0010",
      "category": "listings",
      "brand": "terra-lotus",
      "slug": "listing-0010",
      "alt": "Amazon listing hero with product shot and infographic tiles",
      "width": 2048,
      "height": 2048,
      "blurDataURL": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADQAQCdASoQABAABABoJaACdAClLMv8AAD7vSaAcnEZQCLhC87bkcxfot2Fr7gcdZuTJ+BdlbA98pq6UEWmal+OmxEA0L+oNeqoBPOf/yh+MJj+qrSs4kAAAAA=",
      "variants": {
        "800": "/gallery/listings/listing-0010-800.webp",
        "1600": "/gallery/listings/listing-0010-1600.webp"
      }
    }
  ],
  "lifestyle": [
    {
      "id": "lifestyle/lifestyle-0001",
      "category": "lifestyle",
      "brand": "terra-lotus",
      "slug": "lifestyle-0001",
      "alt": "Lifestyle scene showing product in natural environment",
      "width": 622,
      "height": 647,
      "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAACwAwCdASoQABEAPxFysFAsJqSisAgBgCIJYwC7ACP1f1/ZqMY3AAD+5+01ujTur5Jd4G7Jz7O/7aqdj1mxtmMXW2C3OiuwBGgJUOXa+1MzjRoSysfJYAAA",
      "variants": {
        "800": "/gallery/lifestyle/lifestyle-0001-800.webp",
        "1600": "/gallery/lifestyle/lifestyle-0001-1600.webp"
      }
    },
    {
      "id": "lifestyle/lifestyle-0002",
      "category": "lifestyle",
      "brand": "terra-lotus",
      "slug": "lifestyle-0002",
      "alt": "Lifestyle scene showing product in natural environment",
      "width": 1500,
      "height": 1500,
      "blurDataURL": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAACwAQCdASoQABAABABoJZwAAq9fWTaQAP72E6f444kbJUUbgR1tz8gmfw+1wBvk6jFlkHjSX9SOY2u2fQP3cBo8IchEgAAA",
      "variants": {
        "800": "/gallery/lifestyle/lifestyle-0002-800.webp",
        "1600": "/gallery/lifestyle/lifestyle-0002-1600.webp"
      }
    },
    {
      "id": "lifestyle/lifestyle-0003",
      "category": "lifestyle",
      "brand": "terra-lotus",
      "slug": "lifestyle-0003",
      "alt": "Lifestyle scene showing product in natural environment",
      "width": 1408,
      "height": 768,
      "blurDataURL": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAACwAQCdASoQAAkABABoJQBOgCBuYyqAAP7pA9DNlYVG+TrjSD24fUAQzn3qkozr/7KMBZytK7ablgDgJV3hWxTGGoAAAA==",
      "variants": {
        "800": "/gallery/lifestyle/lifestyle-0003-800.webp",
        "1600": "/gallery/lifestyle/lifestyle-0003-1600.webp"
      }
    },
    {
      "id": "lifestyle/lifestyle-0004",
      "category": "lifestyle",
      "brand": "terra-lotus",
      "slug": "lifestyle-0004",
      "alt": "Lifestyle scene showing product in natural environment",
      "width": 1024,
      "height": 1024,
      "blurDataURL": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAABwAgCdASoQABAABABoJbACdAYwTvskOUV/wqu4AP7zcCI+QycqtmJheuIG8qcUn3eTze47XPoWsN2JcRX5S7v+W9YYed0l0TN/celnIn+W6nVqkoBoXjixK+EbIubh9DxtAAAA",
      "variants": {
        "800": "/gallery/lifestyle/lifestyle-0004-800.webp",
        "1600": "/gallery/lifestyle/lifestyle-0004-1600.webp"
      }
    },
    {
      "id": "lifestyle/lifestyle-0005",
      "category": "lifestyle",
      "brand": "terra-lotus",
      "slug": "lifestyle-0005",
      "alt": "Lifestyle scene showing product in natural environment",
      "width": 1024,
      "height": 1024,
      "blurDataURL": "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAABQAgCdASoQABAABABoJaACdAYv1v2PcgAE0wAA/up6I74oCxOV4oZ7CRXXe9yWDcu+C77j2sNlOGWX56rT5kFwKLPmbiZVXltbchWYkWjl/RrHehPr3KFGWvuhLAIhxenMSBisQWyAERb7Alh9ymiwAAA=",
      "variants": {
        "800": "/gallery/lifestyle/lifestyle-0005-800.webp",
        "1600": "/gallery/lifestyle/lifestyle-0005-1600.webp"
      }
    },
    {
      "id": "lifestyle/lifestyle-0006",
      "category": "lifestyle",
      "brand": "terra-lotus",
      "slug": "lifestyle-0006",
      "alt": "Lifestyle scene showing product in natural environment",
      "width": 2816,
      "height": 1536,
      "blurDataURL": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAAAQAgCdASoQAAkABABoJQBOgCICrOLB5yIoAP7pIJNI5dJy6MhxFN/mwe+s9DxVEcj47wEAgjy4rEHD3yJZePPdc80dgAAA",
      "variants": {
        "800": "/gallery/lifestyle/lifestyle-0006-800.webp",
        "1600": "/gallery/lifestyle/lifestyle-0006-1600.webp"
      }
    },
    {
      "id": "lifestyle/lifestyle-0007",
      "category": "lifestyle",
      "brand": "terra-lotus",
      "slug": "lifestyle-0007",
      "alt": "Lifestyle scene showing product in natural environment",
      "width": 532,
      "height": 532,
      "blurDataURL": "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAACwAgCdASoQABAABABoJYgCsB2gDYqNaWvh0lRc/YAA/vYR9y69KFMK9iQUlM/E7dOg0hz8G34EfyqaS2liN8Wuc0Ww5qRZupn4ZSwbOy4zRSEr7T6uhB7+3/xEsRTvtINpT/NhdLJeJSNk1NAAAA==",
      "variants": {
        "800": "/gallery/lifestyle/lifestyle-0007-800.webp",
        "1600": "/gallery/lifestyle/lifestyle-0007-1600.webp"
      }
    },
    {
      "id": "lifestyle/lifestyle-0008",
      "category": "lifestyle",
      "brand": "terra-lotus",
      "slug": "lifestyle-0008",
      "alt": "Lifestyle scene showing product in natural environment",
      "width": 488,
      "height": 527,
      "blurDataURL": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAACwAwCdASoQABEAPxFysFAsJqSisAgBgCIJZQC3uCG9G837fHQbAAD+bL6eWP96Az6Pzx4a0qkASAjyXmhMdPx0xIlp7vBTHH1jsbh75/k0ydeu0uxDgAuvp4jf0AAA",
      "variants": {
        "800": "/gallery/lifestyle/lifestyle-0008-800.webp",
        "1600": "/gallery/lifestyle/lifestyle-0008-1600.webp"
      }
    },
    {
      "id": "lifestyle/lifestyle-0009",
      "category": "lifestyle",
      "brand": "terra-lotus",
      "slug": "lifestyle-0009",
      "alt": "Lifestyle scene showing product in natural environment",
      "width": 2048,
      "height": 2048,
      "blurDataURL": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAABwAgCdASoQABAABABoJagCdAYvXq/REM8CKuwAAP7YQK4HkVuBU/Ql4pVMGqnKPx+i/v+8j2anoL0qWmDQDJoGMj2CzNUWOZ9WvwWwmhTSCJGnelmiaUTywOgVVCAA",
      "variants": {
        "800": "/gallery/lifestyle/lifestyle-0009-800.webp",
        "1600": "/gallery/lifestyle/lifestyle-0009-1600.webp"
      }
    },
    {
      "id": "lifestyle/lifestyle-0010",
      "category": "lifestyle",
      "brand": "terra-lotus",
      "slug": "lifestyle-0010",
      "alt": "Lifestyle scene showing product in natural environment",
      "width": 2048,
      "height": 2048,
      "blurDataURL": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAwAgCdASoQABAABABoJbACdADHlHzuN5LIgAD+ahjgzfXzZrBssWaujDSif2GKfRY6FyVV16Cq5LHwudqYqXHI8aJYJyyf7Hl3H3KfiMeOAf1k+QAAAA==",
      "variants": {
        "800": "/gallery/lifestyle/lifestyle-0010-800.webp",
        "1600": "/gallery/lifestyle/lifestyle-0010-1600.webp"
      }
    },
    {
      "id": "lifestyle/lifestyle-0011",
      "category": "lifestyle",
      "brand": "terra-lotus",
      "slug": "lifestyle-0011",
      "alt": "Lifestyle scene showing product in natural environment",
      "width": 864,
      "height": 1184,
      "blurDataURL": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAADQAwCdASoQABYAPxFysFAsJqSisAgBgCIJYwCdABoIndFDO0vl+9QA4n3EaR203uesEDs8/eE82lo3GfCQJ8+IrIJWQJcEsx5Gm4r02uV2U/wGhUTHiQ2ehMsQVvRfa51TcvWz66rXdbWGEaJBVA+I1yFlmXAA",
      "variants": {
        "800": "/gallery/lifestyle/lifestyle-0011-800.webp",
        "1600": "/gallery/lifestyle/lifestyle-0011-1600.webp"
      }
    },
    {
      "id": "lifestyle/lifestyle-0012",
      "category": "lifestyle",
      "brand": "terra-lotus",
      "slug": "lifestyle-0012",
      "alt": "Lifestyle scene showing product in natural environment",
      "width": 1620,
      "height": 2160,
      "blurDataURL": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAACQAwCdASoQABUAPxFysFAsJqSisAgBgCIJZwDDNB48wkfT7pVIAPxdqJu611JwyQcBTAfeJK0KwahqNzFHakiPV2L6IFq+rb9gxUqM/A3bBwfz9f/wZDmNej4Of2W5If0E6Jrpi38T+AAA",
      "variants": {
        "800": "/gallery/lifestyle/lifestyle-0012-800.webp",
        "1600": "/gallery/lifestyle/lifestyle-0012-1600.webp"
      }
    },
    {
      "id": "lifestyle/lifestyle-0013",
      "category": "lifestyle",
      "brand": "terra-lotus",
      "slug": "lifestyle-0013",
      "alt": "Lifestyle scene showing product in natural environment",
      "width": 1620,
      "height": 2160,
      "blurDataURL": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAADQAwCdASoQABUAPxFysFAsJqSisAgBgCIJZwAAUAd9XiNAmO3lbQAA/dJj8GRV3mxFrsD+aqyY8LXguZ5YkyUOmzxjgLfiMkxowpeX0SAxUmKL9zQxyJJKn98H60OjgO2VlikGF8K71j7+1qugAAAA",
      "variants": {
        "800": "/gallery/lifestyle/lifestyle-0013-800.webp",
        "1600": "/gallery/lifestyle/lifestyle-0013-1600.webp"
      }
    },
    {
      "id": "lifestyle/lifestyle-0014",
      "category": "lifestyle",
      "brand": "terra-lotus",
      "slug": "lifestyle-0014",
      "alt": "Lifestyle scene showing product in natural environment",
      "width": 1728,
      "height": 2304,
      "blurDataURL": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAABQBACdASoQABUAPxFysFAsJqSisAgBgCIJYgCdMoC4AAm4OteRiTF7QtxgAP7uoZu+Lk0JbX9MS7YDbtjG+VdKfSpHed+kucPEtGockOBoIFFNcsj3iJ3+VLIBPD0nkCNKVW+i4TOZ66wbIAKsfvbJPIAAAA==",
      "variants": {
        "800": "/gallery/lifestyle/lifestyle-0014-800.webp",
        "1600": "/gallery/lifestyle/lifestyle-0014-1600.webp"
      }
    }
  ],
  "white-bg": [
    {
      "id": "white-bg/main-white-0001",
      "category": "white-bg",
      "brand": "terra-lotus",
      "slug": "main-white-0001",
      "alt": "White-background product photography for marketplace listing",
      "width": 1024,
      "height": 1024,
      "blurDataURL": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAACwAQCdASoQABAABABoJZwAAua3walAAP7ziIccXK7b/qW0kUWp3XPcjF3Cn+84l9eLn92irc6erg6g4AA=",
      "variants": {
        "800": "/gallery/white-bg/main-white-0001-800.webp",
        "1600": "/gallery/white-bg/main-white-0001-1600.webp"
      }
    },
    {
      "id": "white-bg/main-white-0002",
      "category": "white-bg",
      "brand": "terra-lotus",
      "slug": "main-white-0002",
      "alt": "White-background product photography for marketplace listing",
      "width": 2160,
      "height": 2160,
      "blurDataURL": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAAAQAgCdASoQABAABABoJaACdAYsjlbesj1AAP7tIFKWYD9YEDd9xPmOjA4OunXf/n53CycPmnptQAykyCTXwM0ngCFJrfA2+5MDz7N953bwy9Aq5UdfOu0AAAA=",
      "variants": {
        "800": "/gallery/white-bg/main-white-0002-800.webp",
        "1600": "/gallery/white-bg/main-white-0002-1600.webp"
      }
    },
    {
      "id": "white-bg/main-white-0003",
      "category": "white-bg",
      "brand": "terra-lotus",
      "slug": "main-white-0003",
      "alt": "White-background product photography for marketplace listing",
      "width": 4096,
      "height": 4096,
      "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAACwAQCdASoQABAABABoJQBOgCFi9wgAAP6UPeudHYnWiZQo4BvK+076/r8OR9npl2c6tI2WafUbtIBtEhvRAtDLEmDpZWOJVK6EShYA",
      "variants": {
        "800": "/gallery/white-bg/main-white-0003-800.webp",
        "1600": "/gallery/white-bg/main-white-0003-1600.webp"
      }
    },
    {
      "id": "white-bg/main-white-0004",
      "category": "white-bg",
      "brand": "terra-lotus",
      "slug": "main-white-0004",
      "alt": "White-background product photography for marketplace listing",
      "width": 2048,
      "height": 2048,
      "blurDataURL": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAABQAgCdASoQABAABABoJaACdAELY1Gd7cwxQQAA/rO1UBpe5mjRIp0LYU/YqI66q4ExQ1Jlqp7xQZMMxzMYmqBPGrPrSzt5trqV2RpYU3Kcaazpc7AAAA==",
      "variants": {
        "800": "/gallery/white-bg/main-white-0004-800.webp",
        "1600": "/gallery/white-bg/main-white-0004-1600.webp"
      }
    },
    {
      "id": "white-bg/main-white-0005",
      "category": "white-bg",
      "brand": "terra-lotus",
      "slug": "main-white-0005",
      "alt": "White-background product photography for marketplace listing",
      "width": 2048,
      "height": 2048,
      "blurDataURL": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAAAQAgCdASoQABAABABoJYgCdADwrM1LrcMAAP6NMKR3VP5aO9shCg0hkxyGJdZzSIOF83TnwHH2uULh5bS8JQKduRDsWw2KyXJI9mB+A0yNxyQOPK3q7NDbAAA=",
      "variants": {
        "800": "/gallery/white-bg/main-white-0005-800.webp",
        "1600": "/gallery/white-bg/main-white-0005-1600.webp"
      }
    },
    {
      "id": "white-bg/main-white-0006",
      "category": "white-bg",
      "brand": "terra-lotus",
      "slug": "main-white-0006",
      "alt": "White-background product photography for marketplace listing",
      "width": 2048,
      "height": 2048,
      "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADwAQCdASoQABAABABoJZQAAtul3wA4/iAA/sRRt19IK0nkT9El/5F5FvIpeRashZSK63lMu1mXqH1I25Pl+k/zhb8izq1DtZ7OhQAA",
      "variants": {
        "800": "/gallery/white-bg/main-white-0006-800.webp",
        "1600": "/gallery/white-bg/main-white-0006-1600.webp"
      }
    }
  ]
};

export const SOCIAL_PREVIEW: GalleryEntry[] = [
  {
    "id": "social/lifestyle-0001",
    "category": "lifestyle",
    "brand": "terra-lotus",
    "slug": "lifestyle-0001",
    "alt": "Lifestyle scene showing product in natural environment",
    "width": 622,
    "height": 647,
    "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAACwAwCdASoQABEAPxFysFAsJqSisAgBgCIJYwC7ACP1f1/ZqMY3AAD+5+01ujTur5Jd4G7Jz7O/7aqdj1mxtmMXW2C3OiuwBGgJUOXa+1MzjRoSysfJYAAA",
    "variants": {
      "800": "/gallery/lifestyle/lifestyle-0001-800.webp",
      "1600": "/gallery/lifestyle/lifestyle-0001-1600.webp"
    }
  },
  {
    "id": "social/lifestyle-0002",
    "category": "lifestyle",
    "brand": "terra-lotus",
    "slug": "lifestyle-0002",
    "alt": "Lifestyle scene showing product in natural environment",
    "width": 1500,
    "height": 1500,
    "blurDataURL": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAACwAQCdASoQABAABABoJZwAAq9fWTaQAP72E6f444kbJUUbgR1tz8gmfw+1wBvk6jFlkHjSX9SOY2u2fQP3cBo8IchEgAAA",
    "variants": {
      "800": "/gallery/lifestyle/lifestyle-0002-800.webp",
      "1600": "/gallery/lifestyle/lifestyle-0002-1600.webp"
    }
  },
  {
    "id": "social/lifestyle-0003",
    "category": "lifestyle",
    "brand": "terra-lotus",
    "slug": "lifestyle-0003",
    "alt": "Lifestyle scene showing product in natural environment",
    "width": 1408,
    "height": 768,
    "blurDataURL": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAACwAQCdASoQAAkABABoJQBOgCBuYyqAAP7pA9DNlYVG+TrjSD24fUAQzn3qkozr/7KMBZytK7ablgDgJV3hWxTGGoAAAA==",
    "variants": {
      "800": "/gallery/lifestyle/lifestyle-0003-800.webp",
      "1600": "/gallery/lifestyle/lifestyle-0003-1600.webp"
    }
  },
  {
    "id": "social/lifestyle-0004",
    "category": "lifestyle",
    "brand": "terra-lotus",
    "slug": "lifestyle-0004",
    "alt": "Lifestyle scene showing product in natural environment",
    "width": 1024,
    "height": 1024,
    "blurDataURL": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAABwAgCdASoQABAABABoJbACdAYwTvskOUV/wqu4AP7zcCI+QycqtmJheuIG8qcUn3eTze47XPoWsN2JcRX5S7v+W9YYed0l0TN/celnIn+W6nVqkoBoXjixK+EbIubh9DxtAAAA",
    "variants": {
      "800": "/gallery/lifestyle/lifestyle-0004-800.webp",
      "1600": "/gallery/lifestyle/lifestyle-0004-1600.webp"
    }
  },
  {
    "id": "social/lifestyle-0005",
    "category": "lifestyle",
    "brand": "terra-lotus",
    "slug": "lifestyle-0005",
    "alt": "Lifestyle scene showing product in natural environment",
    "width": 1024,
    "height": 1024,
    "blurDataURL": "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAABQAgCdASoQABAABABoJaACdAYv1v2PcgAE0wAA/up6I74oCxOV4oZ7CRXXe9yWDcu+C77j2sNlOGWX56rT5kFwKLPmbiZVXltbchWYkWjl/RrHehPr3KFGWvuhLAIhxenMSBisQWyAERb7Alh9ymiwAAA=",
    "variants": {
      "800": "/gallery/lifestyle/lifestyle-0005-800.webp",
      "1600": "/gallery/lifestyle/lifestyle-0005-1600.webp"
    }
  },
  {
    "id": "social/lifestyle-0006",
    "category": "lifestyle",
    "brand": "terra-lotus",
    "slug": "lifestyle-0006",
    "alt": "Lifestyle scene showing product in natural environment",
    "width": 2816,
    "height": 1536,
    "blurDataURL": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAAAQAgCdASoQAAkABABoJQBOgCICrOLB5yIoAP7pIJNI5dJy6MhxFN/mwe+s9DxVEcj47wEAgjy4rEHD3yJZePPdc80dgAAA",
    "variants": {
      "800": "/gallery/lifestyle/lifestyle-0006-800.webp",
      "1600": "/gallery/lifestyle/lifestyle-0006-1600.webp"
    }
  },
  {
    "id": "social/lifestyle-0007",
    "category": "lifestyle",
    "brand": "terra-lotus",
    "slug": "lifestyle-0007",
    "alt": "Lifestyle scene showing product in natural environment",
    "width": 532,
    "height": 532,
    "blurDataURL": "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAACwAgCdASoQABAABABoJYgCsB2gDYqNaWvh0lRc/YAA/vYR9y69KFMK9iQUlM/E7dOg0hz8G34EfyqaS2liN8Wuc0Ww5qRZupn4ZSwbOy4zRSEr7T6uhB7+3/xEsRTvtINpT/NhdLJeJSNk1NAAAA==",
    "variants": {
      "800": "/gallery/lifestyle/lifestyle-0007-800.webp",
      "1600": "/gallery/lifestyle/lifestyle-0007-1600.webp"
    }
  },
  {
    "id": "social/lifestyle-0008",
    "category": "lifestyle",
    "brand": "terra-lotus",
    "slug": "lifestyle-0008",
    "alt": "Lifestyle scene showing product in natural environment",
    "width": 488,
    "height": 527,
    "blurDataURL": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAACwAwCdASoQABEAPxFysFAsJqSisAgBgCIJZQC3uCG9G837fHQbAAD+bL6eWP96Az6Pzx4a0qkASAjyXmhMdPx0xIlp7vBTHH1jsbh75/k0ydeu0uxDgAuvp4jf0AAA",
    "variants": {
      "800": "/gallery/lifestyle/lifestyle-0008-800.webp",
      "1600": "/gallery/lifestyle/lifestyle-0008-1600.webp"
    }
  }
];

// Tab → entries — "social" is a curated subset of lifestyle for now.
export const TABS = {
  listings: [...MANIFEST.listings, ...MANIFEST["white-bg"]],
  lifestyle: MANIFEST.lifestyle,
  social: SOCIAL_PREVIEW,
};
